namespace: community
name: libvirt
version: 0.1.0
readme: README.rst
authors:
  - Ansible (https://github.com/ansible)
description: null
license: GPL-3.0
tags:
  - libvirt
  - lxc
  - qemu
  - virtualbox
dependencies: {}
repository: https://github.com/ansible-collections/libvirt
documentation: https://github.com/ansible-collections/libvirt/tree/master/docs
homepage: https://github.com/ansible-collections/libvirt
issues: https://github.com/ansible-collections/libvirt/issues
